<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class OfficeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $offices = [
            ['id' => 1, 'name' => 'IGP Office', 'type' => 'Office', 'parent_id' => null],
            ['id' => 2, 'name' => 'PLHQ CPO Islamabad', 'type' => 'PLHQ', 'parent_id' => 1],
            ['id' => 3, 'name' => 'Drivers Licensing Authority, Islamabad ', 'type' => 'Office', 'parent_id' => 1],
            ['id' => 4, 'name' => 'DIG Operations', 'type' => 'Office', 'parent_id' => 1],
            ['id' => 5, 'name' => 'DIG HRM', 'type' => 'Office', 'parent_id' => 1],
            ['id' => 6, 'name' => 'DIG HQs', 'type' => 'Office', 'parent_id' => 1],
            ['id' => 7, 'name' => 'R&I Branch CPO HQ', 'type' => 'Office', 'parent_id' => 1],
            ['id' => 8, 'name' => 'Training College Shaikhupura', 'type' => 'Office', 'parent_id' => 1],
            ['id' => 9, 'name' => 'SO to IGP', 'type' => 'Office', 'parent_id' => 1],
            ['id' => 10, 'name' => 'PA to IGP', 'type' => 'Office', 'parent_id' => 1],
            ['id' => 11, 'name' => 'AIG Operations', 'type' => 'Office', 'parent_id' => 4],
            ['id' => 12, 'name' => 'AIG IT', 'type' => 'Office', 'parent_id' => 4],
            ['id' => 13, 'name' => 'AIG HRM', 'type' => 'Office', 'parent_id' => 5],
            ['id' => 14, 'name' => 'AIG Fincance', 'type' => 'Office', 'parent_id' => 6],
            ['id' => 15, 'name' => 'AIG Logistics', 'type' => 'Office', 'parent_id' => 6],
            ['id' => 16, 'name' => 'AIG Legal', 'type' => 'Office', 'parent_id' => 6],
            ['id' => 17, 'name' => 'SP HQs', 'type' => 'Office', 'parent_id' => 6],
            ['id' => 18, 'name' => 'CMO HQs', 'type' => 'Office', 'parent_id' => 6],
            ['id' => 19, 'name' => 'Director PDR', 'type' => 'Office', 'parent_id' => 6],
            ['id' => 20, 'name' => 'Director Monitoring', 'type' => 'Office', 'parent_id' => 6],
            ['id' => 21, 'name' => 'DSP Operations', 'type' => 'Office', 'parent_id' => 11],
            ['id' => 22, 'name' => 'DSP M&E', 'type' => 'Office', 'parent_id' => 11],
            ['id' => 23, 'name' => 'DSP DLA', 'type' => 'Office', 'parent_id' => 11],
            ['id' => 24, 'name' => 'DSP Tele', 'type' => 'Office', 'parent_id' => 11],
            ['id' => 25, 'name' => 'DSP IT', 'type' => 'Office', 'parent_id' => 12],
            ['id' => 26, 'name' => 'CTO IT', 'type' => 'Office', 'parent_id' => 12],
            ['id' => 27, 'name' => 'DD HRM', 'type' => 'Office', 'parent_id' => 13],
            ['id' => 28, 'name' => 'DD Admin', 'type' => 'Office', 'parent_id' => 13],
            ['id' => 29, 'name' => 'AD Admin', 'type' => 'Office', 'parent_id' => 13],
            ['id' => 30, 'name' => 'Incharge Training Branch HRM', 'type' => 'Office', 'parent_id' => 13],
            ['id' => 31, 'name' => 'DD Accounts', 'type' => 'Office', 'parent_id' => 14],
            ['id' => 32, 'name' => 'DD Audit', 'type' => 'Office', 'parent_id' => 14],
            ['id' => 33, 'name' => 'DD Budget', 'type' => 'Office', 'parent_id' => 14],
            ['id' => 34, 'name' => 'DD R&W Func', 'type' => 'Office', 'parent_id' => 14],
            ['id' => 35, 'name' => 'DD RS Fund', 'type' => 'Office', 'parent_id' => 14],
            ['id' => 36, 'name' => 'DSP HQs', 'type' => 'Office', 'parent_id' => 17],
            ['id' => 37, 'name' => 'DSP MT HQs', 'type' => 'Office', 'parent_id' => 17],
            ['id' => 38, 'name' => 'DSP Technical HQs', 'type' => 'Office', 'parent_id' => 17],
            ['id' => 39, 'name' => 'Incharge Misc. Store', 'type' => 'Office', 'parent_id' => 17],
            ['id' => 40, 'name' => 'Complaint Cell PMDU', 'type' => 'Office', 'parent_id' => 22],
            ['id' => 41, 'name' => 'Incharge R&W Fund', 'type' => 'Office', 'parent_id' => 34],
            ['id' => 42, 'name' => 'Incharge RS Fund', 'type' => 'Office', 'parent_id' => 35],
            ['id' => 43, 'name' => 'North Region', 'type' => 'Region', 'parent_id' => 1],
            ['id' => 44, 'name' => 'Motorway North', 'type' => 'Zone', 'parent_id' => 43],
            ['id' => 45, 'name' => 'E35', 'type' => 'Sector', 'parent_id' => 44],
            ['id' => 46, 'name' => 'E35', 'type' => 'PLHQ', 'parent_id' => 45],
            ['id' => 47, 'name' => 'Beat-1', 'type' => 'Beat', 'parent_id' => 46],
            ['id' => 48, 'name' => 'Beat-2', 'type' => 'Beat', 'parent_id' => 46],
            ['id' => 49, 'name' => 'Beat-3', 'type' => 'Beat', 'parent_id' => 46],
            ['id' => 50, 'name' => 'Beat-4', 'type' => 'Beat', 'parent_id' => 46],
            ['id' => 51, 'name' => 'M1', 'type' => 'Sector', 'parent_id' => 44],
            ['id' => 52, 'name' => 'M1', 'type' => 'PLHQ', 'parent_id' => 51],
            ['id' => 53, 'name' => 'Beat-1', 'type' => 'Beat', 'parent_id' => 52],
            ['id' => 54, 'name' => 'Beat-2', 'type' => 'Beat', 'parent_id' => 52],
            ['id' => 55, 'name' => 'Beat-3', 'type' => 'Beat', 'parent_id' => 52],
            ['id' => 56, 'name' => 'Beat-04', 'type' => 'Beat', 'parent_id' => 52],
            ['id' => 57, 'name' => 'M2 North', 'type' => 'Sector', 'parent_id' => 44],
            ['id' => 58, 'name' => 'M2 North', 'type' => 'PLHQ', 'parent_id' => 57],
            ['id' => 59, 'name' => 'Beat-05', 'type' => 'Beat', 'parent_id' => 58],
            ['id' => 60, 'name' => 'Beat-06', 'type' => 'Beat', 'parent_id' => 58],
            ['id' => 61, 'name' => 'Beat-07', 'type' => 'Beat', 'parent_id' => 58],
            ['id' => 62, 'name' => 'Beat-08', 'type' => 'Beat', 'parent_id' => 58],
            ['id' => 63, 'name' => 'Sector-1 M14', 'type' => 'Sector', 'parent_id' => 44],
            ['id' => 64, 'name' => 'Sector-1 M14', 'type' => 'PLHQ', 'parent_id' => 63],
            ['id' => 65, 'name' => 'Beat1 M14', 'type' => 'Beat', 'parent_id' => 64],
            ['id' => 66, 'name' => 'Beat2 M14', 'type' => 'Beat', 'parent_id' => 64],
            ['id' => 67, 'name' => 'Beat 3 M14', 'type' => 'Beat', 'parent_id' => 64],
            ['id' => 68, 'name' => 'Beat4 M14', 'type' => 'Beat', 'parent_id' => 64],
            ['id' => 69, 'name' => 'Beat5 M14', 'type' => 'Beat', 'parent_id' => 64],
            ['id' => 70, 'name' => 'Swat Expressway', 'type' => 'Sector', 'parent_id' => 44],
            ['id' => 71, 'name' => 'Swat Expressway', 'type' => 'PLHQ', 'parent_id' => 70],
            ['id' => 72, 'name' => 'Beat 1 SEW', 'type' => 'Beat', 'parent_id' => 71],
            ['id' => 73, 'name' => 'Beat 2 SEW', 'type' => 'Beat', 'parent_id' => 71],
            ['id' => 74, 'name' => 'N5 North', 'type' => 'Zone', 'parent_id' => 43],
            ['id' => 75, 'name' => 'IMDC', 'type' => 'Sector', 'parent_id' => 74],
            ['id' => 76, 'name' => 'IMDC', 'type' => 'PLHQ', 'parent_id' => 75],
            ['id' => 77, 'name' => 'Beat-IMDC', 'type' => 'Beat', 'parent_id' => 76],
            ['id' => 78, 'name' => 'North 1', 'type' => 'Sector', 'parent_id' => 74],
            ['id' => 79, 'name' => 'North 1', 'type' => 'PLHQ', 'parent_id' => 78],
            ['id' => 80, 'name' => 'Beat-01', 'type' => 'Beat', 'parent_id' => 79],
            ['id' => 81, 'name' => 'Beat-02', 'type' => 'Beat', 'parent_id' => 79],
            ['id' => 82, 'name' => 'Beat-03', 'type' => 'Beat', 'parent_id' => 79],
            ['id' => 83, 'name' => 'Beat-04', 'type' => 'Beat', 'parent_id' => 79],
            ['id' => 84, 'name' => 'North 2', 'type' => 'Sector', 'parent_id' => 74],
            ['id' => 85, 'name' => 'North 2', 'type' => 'PLHQ', 'parent_id' => 84],
            ['id' => 86, 'name' => 'Beat-05', 'type' => 'Beat', 'parent_id' => 85],
            ['id' => 87, 'name' => 'Beat-06', 'type' => 'Beat', 'parent_id' => 85],
            ['id' => 88, 'name' => 'Beat-07', 'type' => 'Beat', 'parent_id' => 85],
            ['id' => 89, 'name' => 'North 3', 'type' => 'Sector', 'parent_id' => 74],
            ['id' => 90, 'name' => 'North 3', 'type' => 'PLHQ', 'parent_id' => 89],
            ['id' => 91, 'name' => 'Beat-08', 'type' => 'Beat', 'parent_id' => 90],
            ['id' => 92, 'name' => 'Beat-09', 'type' => 'Beat', 'parent_id' => 90],
            ['id' => 93, 'name' => 'Beat-10', 'type' => 'Beat', 'parent_id' => 90],
            ['id' => 94, 'name' => 'Beat-11', 'type' => 'Beat', 'parent_id' => 90],
            ['id' => 95, 'name' => 'Central Region', 'type' => 'Region', 'parent_id' => 1],
            ['id' => 96, 'name' => 'N5 Central', 'type' => 'Zone', 'parent_id' => 95],
            ['id' => 97, 'name' => 'Central 1', 'type' => 'Sector', 'parent_id' => 96],
            ['id' => 98, 'name' => 'Central 1', 'type' => 'PLHQ', 'parent_id' => 97],
            ['id' => 99, 'name' => 'Beat-12', 'type' => 'Beat', 'parent_id' => 98],
            ['id' => 100, 'name' => 'Beat-13', 'type' => 'Beat', 'parent_id' => 98],
            ['id' => 101, 'name' => 'Beat-14', 'type' => 'Beat', 'parent_id' => 98],
            ['id' => 102, 'name' => 'Beat-15', 'type' => 'Beat', 'parent_id' => 98],
            ['id' => 103, 'name' => 'Beat-16', 'type' => 'Beat', 'parent_id' => 98],
            ['id' => 104, 'name' => 'Central 2', 'type' => 'Sector', 'parent_id' => 96],
            ['id' => 105, 'name' => 'Central 2', 'type' => 'PLHQ', 'parent_id' => 104],
            ['id' => 106, 'name' => 'Beat-17', 'type' => 'Beat', 'parent_id' => 105],
            ['id' => 107, 'name' => 'Beat-18', 'type' => 'Beat', 'parent_id' => 105],
            ['id' => 108, 'name' => 'Beat-19', 'type' => 'Beat', 'parent_id' => 105],
            ['id' => 109, 'name' => 'Beat-20', 'type' => 'Beat', 'parent_id' => 105],
            ['id' => 110, 'name' => 'Central 3', 'type' => 'Sector', 'parent_id' => 96],
            ['id' => 111, 'name' => 'Central 3', 'type' => 'PLHQ', 'parent_id' => 110],
            ['id' => 112, 'name' => 'Beat-21', 'type' => 'Beat', 'parent_id' => 111],
            ['id' => 113, 'name' => 'Beat-22', 'type' => 'Beat', 'parent_id' => 111],
            ['id' => 114, 'name' => 'Beat-23', 'type' => 'Beat', 'parent_id' => 111],
            ['id' => 115, 'name' => 'Beat-24', 'type' => 'Beat', 'parent_id' => 111],
            ['id' => 116, 'name' => 'Motorway central 1', 'type' => 'Zone', 'parent_id' => 95],
            ['id' => 117, 'name' => 'M2 South', 'type' => 'Sector', 'parent_id' => 116],
            ['id' => 118, 'name' => 'M2 South', 'type' => 'PLHQ', 'parent_id' => 117],
            ['id' => 119, 'name' => 'Beat-09', 'type' => 'Beat', 'parent_id' => 118],
            ['id' => 120, 'name' => 'Beat-10', 'type' => 'Beat', 'parent_id' => 118],
            ['id' => 121, 'name' => 'Beat-11', 'type' => 'Beat', 'parent_id' => 118],
            ['id' => 122, 'name' => 'Beat-12', 'type' => 'Beat', 'parent_id' => 118],
            ['id' => 123, 'name' => 'M-3', 'type' => 'Sector', 'parent_id' => 116],
            ['id' => 124, 'name' => 'M-3', 'type' => 'PLHQ', 'parent_id' => 123],
            ['id' => 125, 'name' => 'Beat-13', 'type' => 'Beat', 'parent_id' => 124],
            ['id' => 126, 'name' => 'Beat-14', 'type' => 'Beat', 'parent_id' => 124],
            ['id' => 127, 'name' => 'Beat-15', 'type' => 'Beat', 'parent_id' => 124],
            ['id' => 128, 'name' => 'Beat-16', 'type' => 'Beat', 'parent_id' => 124],
            ['id' => 129, 'name' => 'LSM', 'type' => 'Sector', 'parent_id' => 116],
            ['id' => 130, 'name' => 'LSM', 'type' => 'PLHQ', 'parent_id' => 129],
            ['id' => 131, 'name' => 'Beat-01', 'type' => 'Beat', 'parent_id' => 130],
            ['id' => 132, 'name' => 'Beat-02', 'type' => 'Beat', 'parent_id' => 130],
            ['id' => 133, 'name' => 'Beat-LEBP', 'type' => 'Beat', 'parent_id' => 130],
            ['id' => 134, 'name' => 'Motorway central 2', 'type' => 'Zone', 'parent_id' => 95],
            ['id' => 135, 'name' => 'Sector M-4', 'type' => 'Sector', 'parent_id' => 134],
            ['id' => 136, 'name' => 'Sector M-4', 'type' => 'PLHQ', 'parent_id' => 135],
            ['id' => 137, 'name' => 'Beat-17', 'type' => 'Beat', 'parent_id' => 136],
            ['id' => 138, 'name' => 'Beat-18', 'type' => 'Beat', 'parent_id' => 136],
            ['id' => 139, 'name' => 'Beat-19', 'type' => 'Beat', 'parent_id' => 136],
            ['id' => 140, 'name' => 'Beat-20', 'type' => 'Beat', 'parent_id' => 136],
            ['id' => 141, 'name' => 'Sector-1 M-5', 'type' => 'Sector', 'parent_id' => 134],
            ['id' => 142, 'name' => 'Sector-1 M-5', 'type' => 'PLHQ', 'parent_id' => 141],
            ['id' => 143, 'name' => 'Beat-23', 'type' => 'Beat', 'parent_id' => 142],
            ['id' => 144, 'name' => 'Beat-24', 'type' => 'Beat', 'parent_id' => 142],
            ['id' => 145, 'name' => 'Beat-25', 'type' => 'Beat', 'parent_id' => 142],
            ['id' => 146, 'name' => 'Beat-26', 'type' => 'Beat', 'parent_id' => 142],
            ['id' => 147, 'name' => 'Sector-2 M-5', 'type' => 'Sector', 'parent_id' => 134],
            ['id' => 148, 'name' => 'Sector-2 M-5', 'type' => 'PLHQ', 'parent_id' => 147],
            ['id' => 149, 'name' => 'Beat-27', 'type' => 'Beat', 'parent_id' => 148],
            ['id' => 150, 'name' => 'Beat-28', 'type' => 'Beat', 'parent_id' => 148],
            ['id' => 151, 'name' => 'Beat-29', 'type' => 'Beat', 'parent_id' => 148],
            ['id' => 152, 'name' => 'Beat-30', 'type' => 'Beat', 'parent_id' => 148],
            ['id' => 153, 'name' => 'Sub Sector M4', 'type' => 'Sector', 'parent_id' => 134],
            ['id' => 154, 'name' => 'Sub Sector M4', 'type' => 'PLHQ', 'parent_id' => 153],
            ['id' => 155, 'name' => 'Beat-21', 'type' => 'Beat', 'parent_id' => 154],
            ['id' => 156, 'name' => 'Beat-22', 'type' => 'Beat', 'parent_id' => 154],
            ['id' => 157, 'name' => 'South Region', 'type' => 'Region', 'parent_id' => 1],
            ['id' => 158, 'name' => 'N5 South', 'type' => 'Zone', 'parent_id' => 157],
            ['id' => 159, 'name' => 'South 1', 'type' => 'Sector', 'parent_id' => 158],
            ['id' => 160, 'name' => 'South 1', 'type' => 'PLHQ', 'parent_id' => 159],
            ['id' => 161, 'name' => 'Beat-25', 'type' => 'Beat', 'parent_id' => 160],
            ['id' => 162, 'name' => 'Beat-26', 'type' => 'Beat', 'parent_id' => 160],
            ['id' => 163, 'name' => 'Beat-27', 'type' => 'Beat', 'parent_id' => 160],
            ['id' => 164, 'name' => 'Beat-28', 'type' => 'Beat', 'parent_id' => 160],
            ['id' => 165, 'name' => 'South 2', 'type' => 'Sector', 'parent_id' => 158],
            ['id' => 166, 'name' => 'South 2', 'type' => 'PLHQ', 'parent_id' => 165],
            ['id' => 167, 'name' => 'Beat-29', 'type' => 'Beat', 'parent_id' => 166],
            ['id' => 168, 'name' => 'Beat-30', 'type' => 'Beat', 'parent_id' => 166],
            ['id' => 169, 'name' => 'Beat-31', 'type' => 'Beat', 'parent_id' => 166],
            ['id' => 170, 'name' => 'South 3', 'type' => 'Sector', 'parent_id' => 158],
            ['id' => 171, 'name' => 'South 3', 'type' => 'PLHQ', 'parent_id' => 170],
            ['id' => 172, 'name' => 'Beat-32', 'type' => 'Beat', 'parent_id' => 171],
            ['id' => 173, 'name' => 'Beat-33', 'type' => 'Beat', 'parent_id' => 171],
            ['id' => 174, 'name' => 'Beat-34', 'type' => 'Beat', 'parent_id' => 171],
            ['id' => 175, 'name' => 'Beat-35', 'type' => 'Beat', 'parent_id' => 171],
            ['id' => 176, 'name' => 'lyari express', 'type' => 'Beat', 'parent_id' => 171],
            ['id' => 177, 'name' => 'Sector-1 N-55 Sehwan', 'type' => 'Sector', 'parent_id' => 158],
            ['id' => 178, 'name' => 'Sector-1 N-55 Sehwan', 'type' => 'PLHQ', 'parent_id' => 177],
            ['id' => 179, 'name' => 'Beat-01', 'type' => 'Beat', 'parent_id' => 178],
            ['id' => 180, 'name' => 'Beat-02', 'type' => 'Beat', 'parent_id' => 178],
            ['id' => 181, 'name' => 'Beat-03', 'type' => 'Beat', 'parent_id' => 178],
            ['id' => 182, 'name' => 'Sector-2 N-55 Dadu', 'type' => 'Sector', 'parent_id' => 158],
            ['id' => 183, 'name' => 'Sector-2 N-55 Dadu', 'type' => 'PLHQ', 'parent_id' => 182],
            ['id' => 184, 'name' => 'Beat-04', 'type' => 'Beat', 'parent_id' => 183],
            ['id' => 185, 'name' => 'Beat-05', 'type' => 'Beat', 'parent_id' => 183],
            ['id' => 186, 'name' => 'Beat-06', 'type' => 'Beat', 'parent_id' => 183],
            ['id' => 187, 'name' => 'WEST', 'type' => 'Zone', 'parent_id' => 157],
            ['id' => 188, 'name' => 'West 1 Uthal', 'type' => 'Sector', 'parent_id' => 187],
            ['id' => 189, 'name' => 'West 1 Uthal', 'type' => 'PLHQ', 'parent_id' => 188],
            ['id' => 190, 'name' => 'Beat-01', 'type' => 'Beat', 'parent_id' => 189],
            ['id' => 191, 'name' => 'Beat-02', 'type' => 'Beat', 'parent_id' => 189],
            ['id' => 192, 'name' => 'Beat-03', 'type' => 'Beat', 'parent_id' => 189],
            ['id' => 193, 'name' => 'Beat-04', 'type' => 'Beat', 'parent_id' => 189],
            ['id' => 194, 'name' => 'West 2', 'type' => 'Sector', 'parent_id' => 187],
            ['id' => 195, 'name' => 'West 2', 'type' => 'PLHQ', 'parent_id' => 194],
            ['id' => 196, 'name' => 'Beat-05', 'type' => 'Beat', 'parent_id' => 195],
            ['id' => 197, 'name' => 'Beat-06', 'type' => 'Beat', 'parent_id' => 195],
            ['id' => 198, 'name' => 'Beat-07', 'type' => 'Beat', 'parent_id' => 195],
            ['id' => 199, 'name' => 'Beat-08', 'type' => 'Beat', 'parent_id' => 195],
            ['id' => 200, 'name' => 'Beat-09', 'type' => 'Beat', 'parent_id' => 195],
            ['id' => 201, 'name' => 'West 3', 'type' => 'Sector', 'parent_id' => 187],
            ['id' => 202, 'name' => 'West 3', 'type' => 'PLHQ', 'parent_id' => 201],
            ['id' => 203, 'name' => 'Beat-10', 'type' => 'Beat', 'parent_id' => 202],
            ['id' => 204, 'name' => 'Beat-11', 'type' => 'Beat', 'parent_id' => 202],
            ['id' => 205, 'name' => 'Beat-12', 'type' => 'Beat', 'parent_id' => 202],
            ['id' => 206, 'name' => 'Beat-13', 'type' => 'Beat', 'parent_id' => 202],
            ['id' => 207, 'name' => 'Beat-14', 'type' => 'Beat', 'parent_id' => 202],
            ['id' => 208, 'name' => 'West 4', 'type' => 'Sector', 'parent_id' => 187],
            ['id' => 209, 'name' => 'West 4', 'type' => 'PLHQ', 'parent_id' => 208],
            ['id' => 210, 'name' => 'Beat-01', 'type' => 'Beat', 'parent_id' => 209],
            ['id' => 211, 'name' => 'Beat-02', 'type' => 'Beat', 'parent_id' => 209],
            ['id' => 212, 'name' => 'Beat-03', 'type' => 'Beat', 'parent_id' => 209],
            ['id' => 213, 'name' => 'Beat-04', 'type' => 'Beat', 'parent_id' => 209],
            ['id' => 214, 'name' => 'N-50 Sector-1', 'type' => 'Sector', 'parent_id' => 187],
            ['id' => 215, 'name' => 'N-50 Sector-1', 'type' => 'PLHQ', 'parent_id' => 214],
            ['id' => 216, 'name' => 'Beat-01', 'type' => 'Beat', 'parent_id' => 215],
            ['id' => 217, 'name' => 'Beat-02', 'type' => 'Beat', 'parent_id' => 215],
        ];

        // Temporarily disable foreign key checks to insert with specific IDs
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('offices')->truncate();

        foreach ($offices as $office) {
            DB::table('offices')->insert([
                'id' => $office['id'],
                'uuid' => Str::uuid(),
                'name' => $office['name'],
                'type' => $office['type'],
                'parent_id' => $office['parent_id'],
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }

        DB::statement('SET FOREIGN_KEY_CHECKS=1;');
    }
}
